---
# tasks file for k8s-master
- name: install docker
  package:
    name: "{{ item }}"
    state: present
  loop: 
    - docker
    - iproute-tc

- name: Disable swap since kubernetes can't work with swap enabled
  command: swapoff -a

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes

- name: Configuring Yum repo for k8s
  yum_repository:
    description: Yum for k8s
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
    exclude:
    - kubelet
    - kubeadm
    - kubectl
    
- name: Installing kubeadm
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: Enabling docker and kubelet services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker

- name: copy daemon.json file for changing cgroup driver to systemd
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker service

- meta: flush_handlers

- name: pull config images
  command: sudo kubeadm config images pull

- name: copying k8s conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: refreshing sysctl
  shell: "sysctl --system"  

- name: initializing  kubeadm service
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: yes   

- name: Creating the directory
  file:
    name: "$HOME/.kube"
    state: directory

- name: Copy conf file
  command: "cp  /etc/kubernetes/admin.conf $HOME/.kube/config"
  ignore_errors: yes

- name: Doing some required thing
  shell: "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Installing flannel
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: Generate join command
  shell: "kubeadm token create --print-join-command"
  register: kubeadm_join_command

- name: debugging
  debug:
    var: kubeadm_join_command.stdout
